/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define TIM2_IRQ_NO 28

volatile uint32_t first_edge = 0;

volatile uint32_t second_edge = 0;

volatile uint32_t difference = 0;

volatile uint32_t frequency = 0;

volatile uint8_t capture_flag = 0;

int main(void)
{
    /* Step 1: Enable clock for GPIOA and TIM2 */

    uint32_t RCC_BASE_ADDR = 0x40023800U;

    uint32_t* RCC_AHB1ENR = (uint32_t*)(RCC_BASE_ADDR + 0x30U);

    uint32_t* RCC_APB1ENR = (uint32_t*)(RCC_BASE_ADDR + 0x40U);

    *RCC_AHB1ENR |= (1 << 0);

    *RCC_APB1ENR |= (1 << 0);

    /* Step 2: Configure PA0 as Alternate Function */

    uint32_t GPIOA_BASE_ADDR = 0x40020000U;

    uint32_t* GPIOA_MODER = (uint32_t*)(GPIOA_BASE_ADDR + 0x00U);

    uint32_t* GPIOA_AFRL = (uint32_t*)(GPIOA_BASE_ADDR + 0x20U);

    *GPIOA_MODER &= ~(3 << 0);

    *GPIOA_MODER |= (2 << 0);

    /* AF1 = TIM2 */

    *GPIOA_AFRL &= ~(15 << 0);

    *GPIOA_AFRL |= (1 << 0);

    /* Step 3: Configure TIM2 Input Capture */

    uint32_t TIM2_BASE_ADDR = 0x40000000U;

    uint32_t* TIM2_PSC = (uint32_t*)(TIM2_BASE_ADDR + 0x28U);

    uint32_t* TIM2_ARR = (uint32_t*)(TIM2_BASE_ADDR + 0x2CU);

    uint32_t* TIM2_CCMR1 = (uint32_t*)(TIM2_BASE_ADDR + 0x18U);

    uint32_t* TIM2_CCER = (uint32_t*)(TIM2_BASE_ADDR + 0x20U);

    uint32_t* TIM2_DIER = (uint32_t*)(TIM2_BASE_ADDR + 0x0CU);

    uint32_t* TIM2_CR1 = (uint32_t*)(TIM2_BASE_ADDR + 0x00U);

    *TIM2_PSC = 16 - 1;

    *TIM2_ARR = 0xFFFFFFFF;

    /* CC1 channel configured as input */

    *TIM2_CCMR1 |= (1 << 0);

    /* Rising edge capture */

    *TIM2_CCER &= ~(1 << 1);

    /* Enable Capture */

    *TIM2_CCER |= (1 << 0);

    /* Enable Capture Interrupt */

    *TIM2_DIER |= (1 << 1);

    /* Enable Timer */

    *TIM2_CR1 |= (1 << 0);

    /* Step 4: Enable NVIC */

    uint32_t* NVIC_ISER0 = (uint32_t*)0xE000E100U;

    *NVIC_ISER0 |= (1 << TIM2_IRQ_NO);

    while(1)
    {
        if(difference != 0)
        {
            frequency = 1000000 / difference;
        }
    }
}

void TIM2_IRQHandler(void)
{
    uint32_t TIM2_BASE_ADDR = 0x40000000U;

    uint32_t* TIM2_SR = (uint32_t*)(TIM2_BASE_ADDR + 0x10U);

    uint32_t* TIM2_CCR1 = (uint32_t*)(TIM2_BASE_ADDR + 0x34U);

    if(*TIM2_SR & (1 << 1))
    {
        if(capture_flag == 0)
        {
            first_edge = *TIM2_CCR1;

            capture_flag = 1;
        }
        else
        {
            second_edge = *TIM2_CCR1;

            difference = second_edge - first_edge;

            capture_flag = 0;
        }

        *TIM2_SR &= ~(1 << 1);
    }
}
