/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define TIM3_IRQ_NUM 29

uint32_t  mod = 0;

int main(void)
{


	/* Controlling Microcontroller LEDs similar to Traffic Light */

	/* Green LED -----> PD 12 */
	/* Red LED -----> PD 14 */
	/* Orange LED -----> PD 13 */

	/* Step 1: Enable the clock of GPIOD on AHB1 bus */

	uint32_t RCC_BASE_ADDR = 0x40023800U;

	uint32_t* GPIOD_CLCK_EN = (uint32_t*)(RCC_BASE_ADDR +  0x30U);

	*GPIOD_CLCK_EN |= (1 << 3);

	/* Step 2: Configuring PD12 PD13 and PD 14 as output */

	uint32_t GPIOD_BASE_ADDR = 0x40020C00U;

	uint32_t* GPIOD_MOD_REG = (uint32_t*)(GPIOD_BASE_ADDR + 0x00U);

	*GPIOD_MOD_REG &= ~((3<<24) | (3<<26) | (3<<28));

	*GPIOD_MOD_REG |= ((1<<24) | (1<<26) | (1<<28));   /* Setting PA12- PA14 as output*/

	/* Step 3: Enable the clock of TIM3 */

	uint32_t* TIM3_CLCK_EN = (uint32_t*)(RCC_BASE_ADDR + 0x40U);

	*TIM3_CLCK_EN |= (1 << 1);  /* Enabling clock for TIM3 */

	/* Step 4: Configure PSC (his decides how fast timer count increment) */

	uint32_t TIM3_BASE_ADDR =  0x40000400U;

	uint32_t* TIM3_PSC = (uint32_t*)(TIM3_BASE_ADDR + 0x28U);

	*TIM2_PSC = 83999;  /* Counter increase after every 1 ms */

	/* Step 5: Configure ARR (This decides when timer overflows or when interrupt will trigger and then reset the counter) */

	uint32_t* TIM3_ARR = (uint32_t*)(TIM3_BASE_ADDR + 0x2CU);

	*TIM3_ARR = 1000;   /* Set red light for 3 seconds ..... Means timer increment every 1 ms 3000 times before triggering the interrupt...means interrupt will trigger after 3 sec */

	/* Step 6: Enable update Interrupt.....(TIMx_DIER)....Means after reaching overflow, interrupt should trigger*/

	uint32_t* TIM3_DIER = (uint32_t*)(TIM3_BASE_ADDR + 0x2CU);

	*TIM3_DIER |= (1 << 0);  /* Setting UIE bit */

	/* Configure NVIC for TIM2 ..... same as done for EXTI.....enabling CPU to handle the interrupt of TIM2 */

	uint32_t* NVIC_ISER_BASE_ADDR = (uint32_t*)0xE000E100U;

	*NVIC_ISER_BASE_ADDR |= (1 << TIM3_IRQ_NUM);

	/* Step 7: Start the Timer now:  Enable CEN bit in CR1 register of TIM2 */

	uint32_t* TIM3_CR1 = (uint32_t*)(TIM3_BASE_ADDR + 0x00U);

	*TIM3_CR1 |= (1 << 0);

	while(1){

		if(mod = 0){

			*TIM3_ARR = 2000;

			*TIM3_CR1 &= ~(1 << 0);
			*TIM3_CR1 |= (1 << 0);
		}

		else if(mod = 1){

			*TIM3_ARR = 3000;

			*TIM3_CR1 &= ~(1 << 0);
			*TIM3_CR1 |= (1 << 0);



		}
		else if(mod = 2){

			*TIM3_ARR = 1000;

			*TIM3_CR1 &= ~(1 << 0);
			*TIM3_CR1 |= (1 << 0);
		}
	}

	for(;;);
}


void TIM3_IRQHandler(void){

	uint32_t GPIOD_BASE_ADDR = 0x40020C00U;
	uint32_t TIM3_BASE_ADDR = 0x40000400U;

	uint32_t* GPIOD_ODR = (uint32_t*)(GPIOD_BASE_ADDR +  0x14U);
	uint32_t* TIM3_SR = (uint32_t*)(TIM3_BASE_ADDR + 0x10);

	if(mod = 0){

		*GPIOD_ODR |= (1 << 14);   /*  Red Light */

		*GPIOD_ODR &= ~(1 << 13);  /* Turing off other lights*/
		*GPIOD_ODR &= ~(1 << 12);

		*TIM2_SR &= ~(1 << 0);

		mod = 1;


	}
	else if(mod = 1){
		*GPIOD_ODR |= (1 << 13);   /*  Yellow Light */

		*GPIOD_ODR &= ~(1 << 14);  /* Turing off other lights*/
		*GPIOD_ODR &= ~(1 << 12);

		*TIM2_SR &= ~(1 << 0);

		mod = 2;

	}
	else if(mod = 2){
		*GPIOD_ODR |= (1 << 12); /*  Green Light */

		*GPIOD_ODR &= ~(1 << 14);  /* Turing off other lights*/
		*GPIOD_ODR &= ~(1 << 12);

		*TIM2_SR &= ~(1 << 0);

		mod = 0;

		}





}
