/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define EXTI9_5_IRQ_NO 23
#define TIM2_IRQ_NO 28

volatile uint32_t adc_value = 0;

volatile uint32_t mode = 0;

volatile uint32_t timer_flag = 0;

/* UART Send Function */

void UART_SendChar(char ch)
{
    uint32_t USART2_BASE_ADDR = 0x40004400U;

    uint32_t* USART_SR = (uint32_t*)(USART2_BASE_ADDR + 0x00U);

    uint32_t* USART_DR = (uint32_t*)(USART2_BASE_ADDR + 0x04U);

    while(!(*USART_SR & (1 << 7)));

    *USART_DR = ch;
}

/* UART Send String */

void UART_SendString(char* str)
{
    while(*str)
    {
        UART_SendChar(*str++);
    }
}

/* Simple Integer to UART */

void UART_SendNumber(uint32_t num)
{
    char buffer[10];

    int i = 0;

    if(num == 0)
    {
        UART_SendChar('0');
        return;
    }

    while(num > 0)
    {
        buffer[i++] = (num % 10) + '0';

        num /= 10;
    }

    for(int j = i - 1; j >= 0; j--)
    {
        UART_SendChar(buffer[j]);
    }
}

int main(void)
{
    /* ---------------------------------------------------- */
    /* Step 1: Enable clocks                                */
    /* ---------------------------------------------------- */

    uint32_t RCC_BASE_ADDR = 0x40023800U;

    uint32_t* RCC_AHB1ENR = (uint32_t*)(RCC_BASE_ADDR + 0x30U);

    uint32_t* RCC_APB1ENR = (uint32_t*)(RCC_BASE_ADDR + 0x40U);

    uint32_t* RCC_APB2ENR = (uint32_t*)(RCC_BASE_ADDR + 0x44U);

    *RCC_AHB1ENR |= (1 << 0); /* GPIOA */
    *RCC_AHB1ENR |= (1 << 1); /* GPIOB */

    *RCC_APB1ENR |= (1 << 0);   /* TIM2 */
    *RCC_APB1ENR |= (1 << 17);  /* USART2 */
    *RCC_APB1ENR |= (1 << 21);  /* I2C1 */

    *RCC_APB2ENR |= (1 << 8);   /* ADC1 */
    *RCC_APB2ENR |= (1 << 14);  /* SYSCFG */

    /* ---------------------------------------------------- */
    /* Step 2: GPIO Configuration                           */
    /* ---------------------------------------------------- */

    uint32_t GPIOA_BASE_ADDR = 0x40020000U;

    uint32_t GPIOB_BASE_ADDR = 0x40020400U;

    uint32_t* GPIOA_MODER = (uint32_t*)(GPIOA_BASE_ADDR + 0x00U);

    uint32_t* GPIOA_AFRL  = (uint32_t*)(GPIOA_BASE_ADDR + 0x20U);

    uint32_t* GPIOA_PUPDR = (uint32_t*)(GPIOA_BASE_ADDR + 0x0CU);

    uint32_t* GPIOB_MODER = (uint32_t*)(GPIOB_BASE_ADDR + 0x00U);

    uint32_t* GPIOB_AFRL  = (uint32_t*)(GPIOB_BASE_ADDR + 0x20U);

    uint32_t* GPIOB_OTYPER = (uint32_t*)(GPIOB_BASE_ADDR + 0x04U);

    /* PA0 -> PWM */

    *GPIOA_MODER |= (2 << 0);

    *GPIOA_AFRL |= (1 << 0);

    /* PA1 -> ADC */

    *GPIOA_MODER |= (3 << 2);

    /* PA2 PA3 -> UART */

    *GPIOA_MODER |= (2 << 4) | (2 << 6);

    *GPIOA_AFRL |= (7 << 8) | (7 << 12);

    /* PA7 -> Button Input */

    *GPIOA_MODER &= ~(3 << 14);

    *GPIOA_PUPDR |= (1 << 14);

    /* PB6 PB7 -> I2C */

    *GPIOB_MODER |= (2 << 12) | (2 << 14);

    *GPIOB_OTYPER |= (1 << 6) | (1 << 7);

    *GPIOB_AFRL |= (4 << 24) | (4 << 28);

    /* ---------------------------------------------------- */
    /* Step 3: Configure USART2                             */
    /* ---------------------------------------------------- */

    uint32_t USART2_BASE_ADDR = 0x40004400U;

    uint32_t* USART_BRR = (uint32_t*)(USART2_BASE_ADDR + 0x08U);

    uint32_t* USART_CR1 = (uint32_t*)(USART2_BASE_ADDR + 0x0CU);

    *USART_BRR = 0x0683;

    *USART_CR1 |= (1 << 2);

    *USART_CR1 |= (1 << 3);

    *USART_CR1 |= (1 << 13);

    /* ---------------------------------------------------- */
    /* Step 4: Configure ADC1                               */
    /* ---------------------------------------------------- */

    uint32_t ADC1_BASE_ADDR = 0x40012000U;

    uint32_t* ADC_CR2 = (uint32_t*)(ADC1_BASE_ADDR + 0x08U);

    uint32_t* ADC_SR = (uint32_t*)(ADC1_BASE_ADDR + 0x00U);

    uint32_t* ADC_SQR3 = (uint32_t*)(ADC1_BASE_ADDR + 0x34U);

    uint32_t* ADC_DR = (uint32_t*)(ADC1_BASE_ADDR + 0x4CU);

    *ADC_SQR3 = 1;

    *ADC_CR2 |= (1 << 0);

    /* ---------------------------------------------------- */
    /* Step 5: Configure PWM using TIM2                     */
    /* ---------------------------------------------------- */

    uint32_t TIM2_BASE_ADDR = 0x40000000U;

    uint32_t* TIM2_PSC = (uint32_t*)(TIM2_BASE_ADDR + 0x28U);

    uint32_t* TIM2_ARR = (uint32_t*)(TIM2_BASE_ADDR + 0x2CU);

    uint32_t* TIM2_CCR1 = (uint32_t*)(TIM2_BASE_ADDR + 0x34U);

    uint32_t* TIM2_CCMR1 = (uint32_t*)(TIM2_BASE_ADDR + 0x18U);

    uint32_t* TIM2_CCER = (uint32_t*)(TIM2_BASE_ADDR + 0x20U);

    uint32_t* TIM2_DIER = (uint32_t*)(TIM2_BASE_ADDR + 0x0CU);

    uint32_t* TIM2_CR1 = (uint32_t*)(TIM2_BASE_ADDR + 0x00U);

    *TIM2_PSC = 1600 - 1;

    *TIM2_ARR = 1000 - 1;

    *TIM2_CCMR1 |= (6 << 4);

    *TIM2_CCER |= (1 << 0);

    /* Timer Interrupt */

    *TIM2_DIER |= (1 << 0);

    *TIM2_CR1 |= (1 << 0);

    /* ---------------------------------------------------- */
    /* Step 6: Configure I2C1                               */
    /* ---------------------------------------------------- */

    uint32_t I2C1_BASE_ADDR = 0x40005400U;

    uint32_t* I2C_CR1 = (uint32_t*)(I2C1_BASE_ADDR + 0x00U);

    uint32_t* I2C_CR2 = (uint32_t*)(I2C1_BASE_ADDR + 0x04U);

    uint32_t* I2C_CCR = (uint32_t*)(I2C1_BASE_ADDR + 0x1CU);

    uint32_t* I2C_TRISE = (uint32_t*)(I2C1_BASE_ADDR + 0x20U);

    *I2C_CR2 = 16;

    *I2C_CCR = 80;

    *I2C_TRISE = 17;

    *I2C_CR1 |= (1 << 0);

    /* ---------------------------------------------------- */
    /* Step 7: Configure EXTI for PA7                       */
    /* ---------------------------------------------------- */

    uint32_t SYSCFG_BASE_ADDR = 0x40013800U;

    uint32_t* SYSCFG_EXTICR2 = (uint32_t*)(SYSCFG_BASE_ADDR + 0x0CU);

    *SYSCFG_EXTICR2 &= ~(15 << 12);

    uint32_t EXTI_BASE_ADDR = 0x40013C00U;

    uint32_t* EXTI_IMR = (uint32_t*)(EXTI_BASE_ADDR + 0x00U);

    uint32_t* EXTI_FTSR = (uint32_t*)(EXTI_BASE_ADDR + 0x0CU);

    *EXTI_IMR |= (1 << 7);

    *EXTI_FTSR |= (1 << 7);

    /* ---------------------------------------------------- */
    /* Step 8: Enable NVIC Interrupts                       */
    /* ---------------------------------------------------- */

    uint32_t* NVIC_ISER0 = (uint32_t*)0xE000E100U;

    *NVIC_ISER0 |= (1 << EXTI9_5_IRQ_NO);

    *NVIC_ISER0 |= (1 << TIM2_IRQ_NO);

    /* ---------------------------------------------------- */
    /* Step 9: Main Loop                                    */
    /* ---------------------------------------------------- */

    while(1)
    {
        /* ADC Conversion */

        *ADC_CR2 |= (1 << 30);

        while(!(*ADC_SR & (1 << 1)));

        adc_value = *ADC_DR;

        if(mode == 1)
        {
            /* ADC controls PWM brightness */

            *TIM2_CCR1 = adc_value / 4;
        }
        else
        {
            *TIM2_CCR1 = 0;
        }

        /* Periodic UART + I2C update */

        if(timer_flag)
        {
            UART_SendString("ADC = ");

            UART_SendNumber(adc_value);

            UART_SendString("\r\n");

            /* I2C START */

            *I2C_CR1 |= (1 << 8);

            timer_flag = 0;
        }
    }
}

/* ---------------------------------------------------- */
/* GPIO Interrupt Handler                               */
/* ---------------------------------------------------- */

void EXTI9_5_IRQHandler(void)
{
    uint32_t EXTI_BASE_ADDR = 0x40013C00U;

    uint32_t* EXTI_PR = (uint32_t*)(EXTI_BASE_ADDR + 0x14U);

    if(*EXTI_PR & (1 << 7))
    {
        mode ^= 1;

        *EXTI_PR = (1 << 7);
    }
}

/* ---------------------------------------------------- */
/* Timer Interrupt Handler                              */
/* ---------------------------------------------------- */

void TIM2_IRQHandler(void)
{
    uint32_t TIM2_BASE_ADDR = 0x40000000U;

    uint32_t* TIM2_SR = (uint32_t*)(TIM2_BASE_ADDR + 0x10U);

    if(*TIM2_SR & (1 << 0))
    {
        timer_flag = 1;

        *TIM2_SR &= ~(1 << 0);
    }
}
