/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
    /* Step 1: Enable clocks */

    uint32_t RCC_BASE_ADDR = 0x40023800U;

    uint32_t* RCC_AHB1ENR = (uint32_t*)(RCC_BASE_ADDR + 0x30U);
    uint32_t* RCC_APB1ENR = (uint32_t*)(RCC_BASE_ADDR + 0x40U);

    *RCC_AHB1ENR |= (1 << 0);
    *RCC_APB1ENR |= (1 << 17);

    /* Step 2: Configure PA2 and PA3 */

    uint32_t GPIOA_BASE_ADDR = 0x40020000U;

    uint32_t* GPIOA_MODER = (uint32_t*)(GPIOA_BASE_ADDR + 0x00U);
    uint32_t* GPIOA_AFRL  = (uint32_t*)(GPIOA_BASE_ADDR + 0x20U);

    *GPIOA_MODER &= ~((3 << 4) | (3 << 6));
    *GPIOA_MODER |=  ((2 << 4) | (2 << 6));

    *GPIOA_AFRL |= (7 << 8) | (7 << 12);

    /* Step 3: Configure USART2 */

    uint32_t USART2_BASE_ADDR = 0x40004400U;

    uint32_t* USART_SR  = (uint32_t*)(USART2_BASE_ADDR + 0x00U);
    uint32_t* USART_DR  = (uint32_t*)(USART2_BASE_ADDR + 0x04U);
    uint32_t* USART_BRR = (uint32_t*)(USART2_BASE_ADDR + 0x08U);
    uint32_t* USART_CR1 = (uint32_t*)(USART2_BASE_ADDR + 0x0CU);

    *USART_BRR = 0x0683;

    *USART_CR1 |= (1 << 2);
    *USART_CR1 |= (1 << 3);
    *USART_CR1 |= (1 << 13);

    /* Step 4: Echo received data */

    for(;;)
    {
        while(!(*USART_SR & (1 << 5)));

        char data = *USART_DR;

        while(!(*USART_SR & (1 << 7)));

        *USART_DR = data;
    }
}
