/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define TIM2_IRQ_NO 28

volatile uint32_t flag = 0;

int main(void)
{
    /* Step 1: Enable clocks */

    uint32_t RCC_BASE_ADDR = 0x40023800U;

    uint32_t* RCC_AHB1ENR = (uint32_t*)(RCC_BASE_ADDR + 0x30U);

    uint32_t* RCC_APB1ENR = (uint32_t*)(RCC_BASE_ADDR + 0x40U);

    *RCC_AHB1ENR |= (1 << 0);

    *RCC_APB1ENR |= (1 << 0);

    /* Step 2: Configure PA5 */

    uint32_t GPIOA_BASE_ADDR = 0x40020000U;

    uint32_t* GPIOA_MODER = (uint32_t*)(GPIOA_BASE_ADDR + 0x00U);

    uint32_t* GPIOA_ODR = (uint32_t*)(GPIOA_BASE_ADDR + 0x14U);

    *GPIOA_MODER &= ~(3 << 10);

    *GPIOA_MODER |= (1 << 10);

    /* Step 3: Configure TIM2 */

    uint32_t TIM2_BASE_ADDR = 0x40000000U;

    uint32_t* TIM2_PSC = (uint32_t*)(TIM2_BASE_ADDR + 0x28U);

    uint32_t* TIM2_ARR = (uint32_t*)(TIM2_BASE_ADDR + 0x2CU);

    uint32_t* TIM2_DIER = (uint32_t*)(TIM2_BASE_ADDR + 0x0CU);

    uint32_t* TIM2_SR = (uint32_t*)(TIM2_BASE_ADDR + 0x10U);

    uint32_t* TIM2_CR1 = (uint32_t*)(TIM2_BASE_ADDR + 0x00U);

    *TIM2_PSC = 16000 - 1;

    *TIM2_ARR = 1000 - 1;

    /* Update Interrupt Enable */

    *TIM2_DIER |= (1 << 0);

    /* Enable Timer */

    *TIM2_CR1 |= (1 << 0);

    /* Step 4: Enable NVIC */

    uint32_t* NVIC_ISER0 = (uint32_t*)0xE000E100U;

    *NVIC_ISER0 |= (1 << TIM2_IRQ_NO);

    while(1)
    {
        if(flag)
        {
            *GPIOA_ODR ^= (1 << 5);

            flag = 0;
        }
    }
}

void TIM2_IRQHandler(void)
{
    uint32_t TIM2_BASE_ADDR = 0x40000000U;

    uint32_t* TIM2_SR = (uint32_t*)(TIM2_BASE_ADDR + 0x10U);

    if(*TIM2_SR & (1 << 0))
    {
        flag = 1;

        *TIM2_SR &= ~(1 << 0);
    }
}
