/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */

	/* Setting up pin for LED......LED is connected to pin PD9 */

	/* Step 1: Enabling clock of GPIOD in AHB1 bus */

	uint32_t RCC_BASE_ADDR = 0x40023800U;

	uint32_t* AHB1_CLCK_EN_REG = (uint32_t*)(RCC_BASE_ADDR + 0x30U);

	*AHB1_CLCK_EN_REG |= (1 << 3);   /* Enabling clock of GPIO D ....... see page 244*/

	/* Step 2: Set pin PD9 as output */

	uint32_t GPIOD_BASE_ADDR = 0x40020C00U;

	uint32_t* GPIOD_MOD_REG = (uint32_t*)(GPIOD_BASE_ADDR + 0x00U);

	*GPIOD_MOD_REG |= (1 << 18);
	*GPIOD_MOD_REG &= ~(1 << 19);

	/* Step 3 Enable the clock of GPIOA because the button is connected to PA0 */

	*AHB1_CLCK_EN_REG |= (1 << 0);

	/* Step 4: Set PA0 as input */

	uint32_t GPIOA_BASE_ADDR = 0x40020000U;

	uint32_t* GPIOA_MOD_REG = (uint32_t*)(GPIOA_BASE_ADDR + 0x00U);

	*GPIOA_MOD_REG &= ~(1 << 0);
	*GPIOA_MOD_REG &= ~(1 << 1);

	/* Step 5: Configure Pull down resistor */

	uint32_t* GPIOA_PUPD_REG = (uint32_t*)(GPIOA_BASE_ADDR + 0x0CU);

	*GPIOA_PUPD_REG &= ~(1 << 0);
	*GPIOA_PUPD_REG |= (1 << 1);

	/* Step 6: Read the button pressed on PA0 and turn on LED on PD9 */

	uint32_t* GPIOA_IDR_REG = (uint32_t*)(GPIOA_BASE_ADDR + 0x10U);
	uint32_t* GPIOD_ODR_REG = (uint32_t*)(GPIOD_BASE_ADDR + 0x14U);

	while(1){
		while(*GPIOA_IDR_REG & (1 << 0)){

			*GPIOD_ODR_REG |= (1 << 9);
		}

		*GPIOD_ODR_REG &= ~(1 << 9);
	}







	for(;;);
}
