/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */

	/* Step 1: Enabling clock of GPIOA in AHB1 bus */

	uint32_t RCC_BASE_ADDR = 0x40023800U;

	uint32_t* GPIOA_PERI_CLCK_EN = (uint32_t*)(RCC_BASE_ADDR +  0x30U);

	*GPIOA_PERI_CLCK_EN |= (1 << 0);

	/* Step 2: Setting pin PA3 as output */

	uint32_t GPIOA_BASE_ADDR = 0x40020000U;

	uint32_t* GPIOA_PORT_MOD_REG = (uint32_t*)(GPIOA_BASE_ADDR + 0x00U);

	*GPIOA_PORT_MOD_REG |= (1 << 6);
	*GPIOA_PORT_MOD_REG &= ~(1 << 7);

	/* Step 3: Setting PA0 as input as user button connected to PA0 */

	*GPIOA_PORT_MOD_REG &= ~(1 << 0);
	*GPIOA_PORT_MOD_REG &= ~(1 << 1);

	/* Step 4 : Configure Pull down resistor for PA0 */

	uint32_t* GPIOA_PUPD_REG = (uint32_t*)(GPIOA_BASE_ADDR + 0x0CU);

	*GPIOA_PUPD_REG &= ~(1 << 0);
	*GPIOA_PUPD_REG |= (1 << 1);

	/* Step 5: Read the button pressed */

	uint32_t* GPIOA_IDR_REG = (uint32_t*)(GPIOA_BASE_ADDR +  0x10U);
	uint32_t* GPIOA_ODR_REG = (uint32_t*)(GPIOA_BASE_ADDR + 0x14U);

	while(1){

		if(*GPIOA_IDR_REG & ( 1 << 0)){

			*GPIOA_ODR_REG ^= (1 << 3);

		}

		while(*GPIOA_IDR_REG & ( 1 << 0)){

			*GPIOA_ODR_REG ^= (1 << 3);

		}
	}

	for(;;);
}
