/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

volatile uint32_t adc_value = 0;

int main(void)
{
    /* Step 1: Enable clocks */

    uint32_t RCC_BASE_ADDR = 0x40023800U;

    uint32_t* RCC_AHB1ENR = (uint32_t*)(RCC_BASE_ADDR + 0x30U);

    uint32_t* RCC_APB1ENR = (uint32_t*)(RCC_BASE_ADDR + 0x40U);

    uint32_t* RCC_APB2ENR = (uint32_t*)(RCC_BASE_ADDR + 0x44U);

    *RCC_AHB1ENR |= (1 << 0);

    *RCC_APB1ENR |= (1 << 0);

    *RCC_APB2ENR |= (1 << 8);

    /* Step 2: Configure PA1 as Analog */

    uint32_t GPIOA_BASE_ADDR = 0x40020000U;

    uint32_t* GPIOA_MODER = (uint32_t*)(GPIOA_BASE_ADDR + 0x00U);

    uint32_t* GPIOA_AFRL = (uint32_t*)(GPIOA_BASE_ADDR + 0x20U);

    *GPIOA_MODER |= (3 << 2);

    /* Configure PA0 as PWM */

    *GPIOA_MODER |= (2 << 0);

    *GPIOA_AFRL |= (1 << 0);

    /* Step 3: Configure TIM2 PWM */

    uint32_t TIM2_BASE_ADDR = 0x40000000U;

    uint32_t* TIM2_PSC = (uint32_t*)(TIM2_BASE_ADDR + 0x28U);

    uint32_t* TIM2_ARR = (uint32_t*)(TIM2_BASE_ADDR + 0x2CU);

    uint32_t* TIM2_CCR1 = (uint32_t*)(TIM2_BASE_ADDR + 0x34U);

    uint32_t* TIM2_CCMR1 = (uint32_t*)(TIM2_BASE_ADDR + 0x18U);

    uint32_t* TIM2_CCER = (uint32_t*)(TIM2_BASE_ADDR + 0x20U);

    uint32_t* TIM2_CR1 = (uint32_t*)(TIM2_BASE_ADDR + 0x00U);

    *TIM2_PSC = 1600 - 1;

    *TIM2_ARR = 1000 - 1;

    *TIM2_CCMR1 |= (6 << 4);

    *TIM2_CCER |= (1 << 0);

    *TIM2_CR1 |= (1 << 0);

    /* Step 4: Configure ADC */

    uint32_t ADC1_BASE_ADDR = 0x40012000U;

    uint32_t* ADC_SR   = (uint32_t*)(ADC1_BASE_ADDR + 0x00U);

    uint32_t* ADC_CR2  = (uint32_t*)(ADC1_BASE_ADDR + 0x08U);

    uint32_t* ADC_SQR3 = (uint32_t*)(ADC1_BASE_ADDR + 0x34U);

    uint32_t* ADC_DR   = (uint32_t*)(ADC1_BASE_ADDR + 0x4CU);

    *ADC_SQR3 = 1;

    *ADC_CR2 |= (1 << 0);

    /* Step 5: ADC controls PWM */

    while(1)
    {
        *ADC_CR2 |= (1 << 30);

        while(!(*ADC_SR & (1 << 1)));

        adc_value = *ADC_DR;

        *TIM2_CCR1 = adc_value / 4;
    }
}
