/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


/* EXTIx  means interrupt line x for pin number x*/
#define EXTI9_5_IRQ_NO  23

int main(void)
{
    /* Loop forever */

	/* Connect LED on pin PA1 and keypad on PA6 - PA9 */

	/* Step 1: Enable clock for GPIOA*/

	uint32_t RCC_BASE_ADDR = 0x40023800U;

	uint32_t* GPIOA_CLCK_EN =  (uint32_t*)(RCC_BASE_ADDR + 0x30U);

	*GPIOA_CLCK_EN |= (1 << 0);

	/* Step 2: Configure PA1 and PA6 as output and PA7-PA9 as input */

	uint32_t GPIOA_BASE_ADDR = 0x40020000U;

	uint32_t* GPIOA_MOD_REG = (uint32_t*)(GPIOA_BASE_ADDR +  0x00U);

	*GPIOA_MOD_REG &= ~((3 << 14) | (3 << 16) | (3 << 18));   /* Configuring pin PA7 - P9 input*/

	*GPIOA_MOD_REG &= ~(3 << 2);   /* Configuring PA0 as output*/
	*GPIOA_MOD_REG |= (1 << 2);

	*GPIOA_MOD_REG &= ~(3 << 12);   /* Configuring PA6 as output*/
	*GPIOA_MOD_REG |= (1 << 12);

	/* Step 3: Configuring Pull up resistor for PA7-PA9 */

	uint32_t* GPIOA_PUPD_REG = (uint32_t*)(GPIOA_BASE_ADDR +  0x0CU);

	*GPIOA_PUPD_REG &= ~((3 << 14) | (3 << 16) | (3 << 18));
	*GPIOA_PUPD_REG |= ((1 << 14) | (1 << 16) | (1 << 18));

	/* Step 5: Configuring SYSCFG for Interrupt for Interrupt lines...It configure that PA7-PA9 is connected to Interrupt line EXTI7-EXTI9 */

	uint32_t* SYSCFG_BASE_ADDR = (uint32_t*)(0x40013800U);

	uint32_t* SYSCFG_EXTICR2 =  (uint32_t*)(SYSCFG_BASE_ADDR + 0x0CU);
	uint32_t* SYSCFG_EXTICR3 =  (uint32_t*)(SYSCFG_BASE_ADDR + 0x10U);

	*SYSCFG_EXTICR2 &= ~(15 << 12); /* Configuring SYSCFG for PA7 */
	*SYSCFG_EXTICR3 &= ~((15 << 0) | (15 << 4)); /* Configuring SYSCFG for PA8 and PA9 */

	/* Step 5: Enabling Interrupt on Interrupt line (EXTI7 - EXTI9) FOR Pin PA7 - PA9...Means Pin PA7-PA9 is allow to generate interrupt */

	uint32_t EXTI_BASE_ADDR = 0x40013C00U;

	uint32_t* EXTI_IMR = (uint32_t*)(EXTI_BASE_ADDR + 0x00U);

	*EXTI_IMR &= ~((1<<7) | (1<<8) | (1<<9));
	*EXTI_IMR |= ((1<<7) | (1<<8) | (1<<9));    /* Enabling the interrupt for Pin PA7-PA9 */

	/* Step 6: Configuring EXTI Trigger.....Select Falling Edge */

	uint32_t* EXTI_FTSR = (uint32_t*)(EXTI_BASE_ADDR + 0x0CU);

	*EXTI_FTSR &= ~((1<<7) | (1<<8) | (1<<9));
	*EXTI_FTSR |= ((1<<7) | (1<<8) | (1<<9));

	/* Step 7: NVIC enable...(This enable CPU to handle Interrupt...CPU will jump to ISR)..IRQ0 handle IRQ 0 - 31....IRQ 1 handle 32 - 63 etc  */

	uint32_t* NVIC_ISER0 = (uint32_t*)0xE000E100U;   /* See page 219 of user generic guide */

	*NVIC_ISER0 |= (1 << EXTI9_5_IRQ_NO);

	for(;;);
}

void EXTI9_5_IRQHandler(void){

	uint32_t GPIOA_BASE_ADDR = 0x40020000U;
	uint32_t EXTI_BASE_ADDR = 0x40013C00U;

	uint32_t* GPIOA_ODR_REG = (uint32_t*)(GPIOA_BASE_ADDR + 0x14U);

	uint32_t* EXTI_PR = (uint32_t*)(EXTI_BASE_ADDR +  0x14U);


	/* check PA7 */
	    if (*EXTI_PR & (1 << 7))
	    {
	        *GPIOA_ODR_REG ^= (1 << 1);
	        *EXTI_PR = (1 << 7);
	    }

	    /* check PA8 */
	    if (*EXTI_PR & (1 << 8))
	    {
	        *GPIOA_ODR_REG ^= (1 << 1);
	        *EXTI_PR = (1 << 8);
	    }

	    /* check PA9 */
	    if (*EXTI_PR & (1 << 9))
	    {
	        *GPIOA_ODR_REG ^= (1 << 1);
	        *EXTI_PR = (1 << 9);
	    }

}


