/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define ADC_IRQ_NO 18

volatile uint32_t adc_value = 0;

int main(void)
{
    /* Step 1: Enable clocks */

    uint32_t RCC_BASE_ADDR = 0x40023800U;

    uint32_t* RCC_AHB1ENR = (uint32_t*)(RCC_BASE_ADDR + 0x30U);

    uint32_t* RCC_APB2ENR = (uint32_t*)(RCC_BASE_ADDR + 0x44U);

    *RCC_AHB1ENR |= (1 << 0);

    *RCC_APB2ENR |= (1 << 8);

    /* Step 2: Configure PA1 as Analog */

    uint32_t GPIOA_BASE_ADDR = 0x40020000U;

    uint32_t* GPIOA_MODER = (uint32_t*)(GPIOA_BASE_ADDR + 0x00U);

    *GPIOA_MODER |= (3 << 2);

    /* Step 3: Configure ADC */

    uint32_t ADC1_BASE_ADDR = 0x40012000U;

    uint32_t* ADC_CR1  = (uint32_t*)(ADC1_BASE_ADDR + 0x04U);

    uint32_t* ADC_CR2  = (uint32_t*)(ADC1_BASE_ADDR + 0x08U);

    uint32_t* ADC_SQR3 = (uint32_t*)(ADC1_BASE_ADDR + 0x34U);

    *ADC_SQR3 = 1;

    /* Enable EOC Interrupt */

    *ADC_CR1 |= (1 << 5);

    /* Enable ADC */

    *ADC_CR2 |= (1 << 0);

    /* Step 4: Enable NVIC */

    uint32_t* NVIC_ISER0 = (uint32_t*)0xE000E100U;

    *NVIC_ISER0 |= (1 << ADC_IRQ_NO);

    /* Step 5: Start Conversion */

    while(1)
    {
        *ADC_CR2 |= (1 << 30);
    }
}

void ADC_IRQHandler(void)
{
    uint32_t ADC1_BASE_ADDR = 0x40012000U;

    uint32_t* ADC_SR = (uint32_t*)(ADC1_BASE_ADDR + 0x00U);

    uint32_t* ADC_DR = (uint32_t*)(ADC1_BASE_ADDR + 0x4CU);

    if(*ADC_SR & (1 << 1))
    {
        adc_value = *ADC_DR;
    }
}
