/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

char buffer[20];
uint32_t index = 0;

int main(void)
{
    /* Step 1: Enable clocks */

    uint32_t RCC_BASE_ADDR = 0x40023800U;

    uint32_t* RCC_AHB1ENR = (uint32_t*)(RCC_BASE_ADDR + 0x30U);
    uint32_t* RCC_APB1ENR = (uint32_t*)(RCC_BASE_ADDR + 0x40U);

    *RCC_AHB1ENR |= (1 << 0);
    *RCC_APB1ENR |= (1 << 17);

    /* Step 2: Configure GPIO */

    uint32_t GPIOA_BASE_ADDR = 0x40020000U;

    uint32_t* GPIOA_MODER = (uint32_t*)(GPIOA_BASE_ADDR + 0x00U);
    uint32_t* GPIOA_AFRL  = (uint32_t*)(GPIOA_BASE_ADDR + 0x20U);
    uint32_t* GPIOA_ODR   = (uint32_t*)(GPIOA_BASE_ADDR + 0x14U);

    /* USART Pins */

    *GPIOA_MODER |= (2 << 4) | (2 << 6);

    *GPIOA_AFRL |= (7 << 8) | (7 << 12);

    /* LED Pin PA5 */

    *GPIOA_MODER |= (1 << 10);

    /* Step 3: USART Config */

    uint32_t USART2_BASE_ADDR = 0x40004400U;

    uint32_t* USART_SR  = (uint32_t*)(USART2_BASE_ADDR + 0x00U);
    uint32_t* USART_DR  = (uint32_t*)(USART2_BASE_ADDR + 0x04U);
    uint32_t* USART_BRR = (uint32_t*)(USART2_BASE_ADDR + 0x08U);
    uint32_t* USART_CR1 = (uint32_t*)(USART2_BASE_ADDR + 0x0CU);

    *USART_BRR = 0x0683;

    *USART_CR1 |= (1 << 2);
    *USART_CR1 |= (1 << 3);
    *USART_CR1 |= (1 << 13);

    /* Step 4: Parse Commands */

    for(;;)
    {
        while(!(*USART_SR & (1 << 5)));

        char data = *USART_DR;

        if(data != '\r')
        {
            buffer[index++] = data;
        }

        else
        {
            buffer[index] = '\0';

            if(buffer[0] == 'L')
            {
                *GPIOA_ODR |= (1 << 5);
            }

            index = 0;
        }
    }
}
