/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define TIM2_IRQ_NUM 28

int main(void)
{
    /* Loop forever */

	/* Connect the LED to PA4 */

	/* Step 1: Enable the clock of GPIOA in RCC */

	uint32_t RCC_BASE_ADDR = 0x40023800U;

	uint32_t* GPIOA_CLCK_EN = (uint32_t*)(RCC_BASE_ADDR + 0x30U);

	*GPIOA_CLCK_EN &= ~(1 << 0);
	*GPIOA_CLCK_EN |= (1 << 0);

	/* Step 2: Configure PA4 as output */

	uint32_t GPIOA_BASE_ADDR = 0x40020000U;

	uint32_t* GPIOA_MOD_REG = (uint32_t*)(GPIOA_BASE_ADDR + 0x00U);

	*GPIOA_MOD_REG &= ~(3 << 8);
	*GPIOA_MOD_REG |= (1 << 8);  /* Configuring PA4 as output .....01*/

	/* Step 3: Enable the clock of TIM2 in RCC (APB1) */

	uint32_t* TIM2_CLCK_EN =  (uint32_t*)(RCC_BASE_ADDR + 0x40U);

	*TIM2_CLCK_EN &= ~(1 << 0);
	*TIM2_CLCK_EN |= (1 << 0);

	/* Step 4: Configure PSC (This decides how fast timer counts, increment) */

	uint32_t TIM2_BASE_ADDR = 0x40000000U;

	uint32_t* TIM2_PSC = (uint32_t*)(TIM2_BASE_ADDR +  0x28U);

	/* Timer increment every 1 ms */
	*TIM2_PSC = 83999;        /* See google docs for explanation */

	/* Step 5: Configure ARR (This decides when timer overflows or when interrupt will trigger and then reset the counter) */

	uint32_t* TIM2_ARR = (uint32_t*)(TIM2_BASE_ADDR + 0x2CU);

	*TIM2_ARR = 1000;           /* Means timer increment every 1 ms 1000 times before triggering the interrupt...means interrupt will trigger after 1 sec */

	/* STEP 6 : Enable Update Interrupt ( Means Timer reaches to 1000, overflow occur and then counter is reset and interrupt is trigger) */

	uint32_t* TIM2_DIER  = (uint32_t*)(TIM2_BASE_ADDR + 0x0CU);

	*TIM2_DIER |= (1 << 0);   /* We only set UIE bit to enable the interrupt after counter overflow */

	/* Configure NVIC for TIM2 ..... same as done for EXTI.....enabling CPU to handle the interrupt of TIM2 */

	uint32_t* NVIC_ISER_BASE_ADDR = (uint32_t*)0xE000E100U;

	*NVIC_ISER_BASE_ADDR |= (1 << TIM2_IRQ_NUM);

	/* Step 7: Start the Timer now:  Enable CEN bit in CR1 register of TIM2 */

	uint32_t* TIM2_CR1 =  (uint32_t*)(TIM2_BASE_ADDR + 0x00U);

	*TIM2_CR1 |= (1 << 0);   /* Setting CEN bit */

	/* Timer will start as soon as CEN bit is set to 1*/

	while(1){
		/* CPU will stuck here and led keep on blinking */
	}

	for(;;);
}


void TIM2_IRQHandler(void){

	uint32_t GPIOA_BASE_ADDR = 0x40020000U;
	uint32_t TIM2_BASE_ADDR = 0x40000000U;

	uint32_t* GPIOA_ODR =  (uint32_t*)(GPIOA_BASE_ADDR +  0x14U);
	uint32_t* TIM2_SR = (uint32_t*)(TIM2_BASE_ADDR +  0x10U);   /* Work same as of EXTI_PR*/

	/* When timer reaches the ARR and overflows occur, interrupt will trigger UIF bit of TIM2_SR will be set to 1 */
	/* Hence it is necesearry to reset this bit at the end */

	*GPIOA_ODR ^= (1 << 4 );
	*TIM2_SR &= ~(1 << 0);
}
