/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */

	/* Connecting the pins of Keypad Matrix on PA1 - PA7 */

	/* Step 1: Enabling Clock of GPIOA register */

	uint32_t RCC_BASE_ADDR = 0x40023800U;

	uint32_t* GPIOA_CLCK_EN = (uint32_t*)(RCC_BASE_ADDR +  0x30U);

	*GPIOA_CLCK_EN |= (1 << 0);

	/* Step 2: Configuring pin PA1-PA7 as input and output */

	uint32_t GPIOA_BASE_ADDR = 0x40020000U;

	uint32_t* GPIOA_MODE_REG = (uint32_t*)(GPIOA_BASE_ADDR + 0x00U);


	/* Setting pin PA1 - PA4 as Output*/
	// clear BOTH bits first
	*GPIOA_MODE_REG &= ~((3<<2) | (3<<4) | (3<<6) | (3<<8));

	*GPIOA_MODE_REG |= ((1<<2) | (1<<4) | (1<<6) | (1<<8));
	*GPIOA_MODE_REG &= ~((1<<3) | (1<<5) | (1<<7) | (1<<9));


	/* Setting PA5-PA7 as Input */
	*GPIOA_MODE_REG &= ~((1<<10) | (1<<11) | (1<<12) | (1<<13) | (1<<14) | (1<<15));


	/* Step 3: Configure Pull up resistor for all PA1-P7 pins */

	uint32_t* GPIO_PUPD_REG = (uint32_t*)(GPIOA_BASE_ADDR + 0x0CU);

	/* cONFIGURING PA5 - PA7 as pull up resistor */
	*GPIO_PUPD_REG &= ~((3<<10) | (3<<12) | (3<<14));
	/* *GPIO_PUPD_REG |= ((1<<15) | (1<<13) | (1<<11)); */
	*GPIO_PUPD_REG |= (1<<14) | (1<<12) | (1<<10);


	/* Step 4: Configuring ODR (for PA1-PA4) and IDR Register (for PA5-PA7)  */

	uint32_t* GPIOA_IDR_REG = (uint32_t*)(GPIOA_BASE_ADDR + 0x10U);
	uint32_t* GPIOA_ODR_REG = (uint32_t*)(GPIOA_BASE_ADDR + 0x14U);


	while(1){

	    /* -------- ROW 1 -------- */
	    *GPIOA_ODR_REG |= ((1<<1) | (1<<2) | (1<<3) | (1<<4)); // all HIGH
	    *GPIOA_ODR_REG &= ~(1<<1); // Row1 LOW

	    for(volatile int i = 0; i < 1000; i++);

	    if(!(*GPIOA_IDR_REG & (1<<5))) {
	        for(volatile int i=0;i<50000;i++);
	        if(!(*GPIOA_IDR_REG & (1<<5))){
	            printf("1\n");
	            while(!(*GPIOA_IDR_REG & (1<<5)));
	        }
	        continue;
	    }
	    else if(!(*GPIOA_IDR_REG & (1<<6))){
	        for(volatile int i=0;i<50000;i++);
	        if(!(*GPIOA_IDR_REG & (1<<6))){
	            printf("2\n");
	            while(!(*GPIOA_IDR_REG & (1<<6)));
	        }
	        continue;
	    }
	    else if(!(*GPIOA_IDR_REG & (1<<7))){
	        for(volatile int i=0;i<50000;i++);
	        if(!(*GPIOA_IDR_REG & (1<<7))){
	            printf("3\n");
	            while(!(*GPIOA_IDR_REG & (1<<7)));
	        }
	        continue;
	    }

	    /* -------- ROW 2 -------- */
	    *GPIOA_ODR_REG |= ((1<<1) | (1<<2) | (1<<3) | (1<<4));
	    *GPIOA_ODR_REG &= ~(1<<2); // Row2 LOW

	    for(volatile int i = 0; i < 1000; i++);

	    if(!(*GPIOA_IDR_REG & (1<<5))) {
	        for(volatile int i=0;i<50000;i++);
	        if(!(*GPIOA_IDR_REG & (1<<5))){
	            printf("4\n");
	            while(!(*GPIOA_IDR_REG & (1<<5)));
	        }
	        continue;
	    }
	    else if(!(*GPIOA_IDR_REG & (1<<6))){
	        for(volatile int i=0;i<50000;i++);
	        if(!(*GPIOA_IDR_REG & (1<<6))){
	            printf("5\n");
	            while(!(*GPIOA_IDR_REG & (1<<6)));
	        }
	        continue;
	    }
	    else if(!(*GPIOA_IDR_REG & (1<<7))){
	        for(volatile int i=0;i<50000;i++);
	        if(!(*GPIOA_IDR_REG & (1<<7))){
	            printf("6\n");
	            while(!(*GPIOA_IDR_REG & (1<<7)));
	        }
	        continue;
	    }

	    /* -------- ROW 3 -------- */
	    *GPIOA_ODR_REG |= ((1<<1) | (1<<2) | (1<<3) | (1<<4));
	    *GPIOA_ODR_REG &= ~(1<<3); // Row3 LOW

	    for(volatile int i = 0; i < 1000; i++);

	    if(!(*GPIOA_IDR_REG & (1<<5))) {
	        for(volatile int i=0;i<50000;i++);
	        if(!(*GPIOA_IDR_REG & (1<<5))){
	            printf("7\n");
	            while(!(*GPIOA_IDR_REG & (1<<5)));
	        }
	        continue;
	    }
	    else if(!(*GPIOA_IDR_REG & (1<<6))){
	        for(volatile int i=0;i<50000;i++);
	        if(!(*GPIOA_IDR_REG & (1<<6))){
	            printf("8\n");
	            while(!(*GPIOA_IDR_REG & (1<<6)));
	        }
	        continue;
	    }
	    else if(!(*GPIOA_IDR_REG & (1<<7))){
	        for(volatile int i=0;i<50000;i++);
	        if(!(*GPIOA_IDR_REG & (1<<7))){
	            printf("9\n");
	            while(!(*GPIOA_IDR_REG & (1<<7)));
	        }
	        continue;
	    }

	    /* -------- ROW 4 -------- */
	    *GPIOA_ODR_REG |= ((1<<1) | (1<<2) | (1<<3) | (1<<4));
	    *GPIOA_ODR_REG &= ~(1<<4); // Row4 LOW

	    for(volatile int i = 0; i < 1000; i++);

	    if(!(*GPIOA_IDR_REG & (1<<5))) {
	        for(volatile int i=0;i<50000;i++);
	        if(!(*GPIOA_IDR_REG & (1<<5))){
	            printf("*\n");
	            while(!(*GPIOA_IDR_REG & (1<<5)));
	        }
	        continue;
	    }
	    else if(!(*GPIOA_IDR_REG & (1<<6))){
	        for(volatile int i=0;i<50000;i++);
	        if(!(*GPIOA_IDR_REG & (1<<6))){
	            printf("0\n");
	            while(!(*GPIOA_IDR_REG & (1<<6)));
	        }
	        continue;
	    }
	    else if(!(*GPIOA_IDR_REG & (1<<7))){
	        for(volatile int i=0;i<50000;i++);
	        if(!(*GPIOA_IDR_REG & (1<<7))){
	            printf("#\n");
	            while(!(*GPIOA_IDR_REG & (1<<7)));
	        }
	        continue;
	    }
	}


	for(;;);
}
