/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
    /* Step 1: Enable clock for GPIOA and TIM2 */

    uint32_t RCC_BASE_ADDR = 0x40023800U;

    uint32_t* RCC_AHB1ENR = (uint32_t*)(RCC_BASE_ADDR + 0x30U);

    uint32_t* RCC_APB1ENR = (uint32_t*)(RCC_BASE_ADDR + 0x40U);

    *RCC_AHB1ENR |= (1 << 0);

    *RCC_APB1ENR |= (1 << 0);

    /* Step 2: Configure PA0 as Alternate Function */

    uint32_t GPIOA_BASE_ADDR = 0x40020000U;

    uint32_t* GPIOA_MODER = (uint32_t*)(GPIOA_BASE_ADDR + 0x00U);

    uint32_t* GPIOA_AFRL = (uint32_t*)(GPIOA_BASE_ADDR + 0x20U);

    *GPIOA_MODER &= ~(3 << 0);

    *GPIOA_MODER |= (2 << 0);

    /* AF1 = TIM2 */

    *GPIOA_AFRL &= ~(15 << 0);

    *GPIOA_AFRL |= (1 << 0);

    /* Step 3: Configure TIM2 PWM */

    uint32_t TIM2_BASE_ADDR = 0x40000000U;

    uint32_t* TIM2_PSC = (uint32_t*)(TIM2_BASE_ADDR + 0x28U);

    uint32_t* TIM2_ARR = (uint32_t*)(TIM2_BASE_ADDR + 0x2CU);

    uint32_t* TIM2_CCR1 = (uint32_t*)(TIM2_BASE_ADDR + 0x34U);

    uint32_t* TIM2_CCMR1 = (uint32_t*)(TIM2_BASE_ADDR + 0x18U);

    uint32_t* TIM2_CCER = (uint32_t*)(TIM2_BASE_ADDR + 0x20U);

    uint32_t* TIM2_CR1 = (uint32_t*)(TIM2_BASE_ADDR + 0x00U);

    /* PWM Frequency */

    *TIM2_PSC = 1600 - 1;

    *TIM2_ARR = 1000 - 1;

    /* 50% Duty Cycle */

    *TIM2_CCR1 = 500;

    /* PWM Mode 1 */

    *TIM2_CCMR1 |= (6 << 4);

    /* Enable Output Compare */

    *TIM2_CCER |= (1 << 0);

    /* Enable Timer */

    *TIM2_CR1 |= (1 << 0);

    while(1)
    {

    }
}
