/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */

	/* Connecting LED on pin PE4*/

	/* Step 1: Enabling clock for GPIOE */

	uint32_t RCC_BASE_ADDR = 0x40023800U;

	uint32_t* GPIOE_CLCK_EN_REG = (uint32_t*)(RCC_BASE_ADDR + 0x30U);

	*GPIOE_CLCK_EN_REG |= (1 << 4);

	/* Step 2: Setting Pin PE4 as output */

	uint32_t GPIOE_BASE_ADDR = 0x40021000U;

	uint32_t* GPIOE_MOD_REG = (uint32_t*)(GPIOE_BASE_ADDR + 0x00U);

	*GPIOE_MOD_REG |= (1 << 8);    /* We use this |= when the register can read and right.....First it read the register and then perform bitwise OR with the MASK value */
	*GPIOE_MOD_REG &= ~(1 << 9);

	/* Step 3: Writing to BSSR instead of ODR to toggle led */

	uint32_t* GPIOE_BSSR_REG = (uint32_t*)(GPIOE_BASE_ADDR + 0x18U);


	while(1){
	/* To set PE4 ON BSSR */
	*GPIOE_BSSR_REG = (1 << 4); /* We cant use this |= here because BSSR Register cannot be read....It can only be write */

	for(uint32_t i = 0; i < 100000; i++);

	/* To reset PE4 ON BSSR */
	*GPIOE_BSSR_REG = (1 << (4+16));

	for(uint32_t i = 0; i < 100000; i++);
	}
	for(;;);
}
