/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

volatile uint8_t data;

int main(void)
{
    /* Step 1: Enable clocks */

    uint32_t RCC_BASE_ADDR = 0x40023800U;

    uint32_t* RCC_AHB1ENR = (uint32_t*)(RCC_BASE_ADDR + 0x30U);
    uint32_t* RCC_APB1ENR = (uint32_t*)(RCC_BASE_ADDR + 0x40U);

    *RCC_AHB1ENR |= (1 << 1);
    *RCC_APB1ENR |= (1 << 21);

    /* Step 2: Configure PB6 and PB7 */

    uint32_t GPIOB_BASE_ADDR = 0x40020400U;

    uint32_t* GPIOB_MODER  = (uint32_t*)(GPIOB_BASE_ADDR + 0x00U);
    uint32_t* GPIOB_OTYPER = (uint32_t*)(GPIOB_BASE_ADDR + 0x04U);
    uint32_t* GPIOB_AFRL   = (uint32_t*)(GPIOB_BASE_ADDR + 0x20U);

    *GPIOB_MODER |= (2 << 12) | (2 << 14);

    *GPIOB_OTYPER |= (1 << 6) | (1 << 7);

    *GPIOB_AFRL |= (4 << 24) | (4 << 28);

    /* Step 3: Configure I2C */

    uint32_t I2C1_BASE_ADDR = 0x40005400U;

    uint32_t* I2C_CR1   = (uint32_t*)(I2C1_BASE_ADDR + 0x00U);
    uint32_t* I2C_CR2   = (uint32_t*)(I2C1_BASE_ADDR + 0x04U);
    uint32_t* I2C_SR1   = (uint32_t*)(I2C1_BASE_ADDR + 0x14U);
    uint32_t* I2C_SR2   = (uint32_t*)(I2C1_BASE_ADDR + 0x18U);
    uint32_t* I2C_DR    = (uint32_t*)(I2C1_BASE_ADDR + 0x10U);
    uint32_t* I2C_CCR   = (uint32_t*)(I2C1_BASE_ADDR + 0x1CU);
    uint32_t* I2C_TRISE = (uint32_t*)(I2C1_BASE_ADDR + 0x20U);

    *I2C_CR2 = 16;

    *I2C_CCR = 80;

    *I2C_TRISE = 17;

    *I2C_CR1 |= (1 << 0);

    /* ACK Enable */

    *I2C_CR1 |= (1 << 10);

    /* Step 4: START */

    *I2C_CR1 |= (1 << 8);

    while(!(*I2C_SR1 & (1 << 0)));

    /* Step 5: Send Address + Read */

    *I2C_DR = 0xA1;

    while(!(*I2C_SR1 & (1 << 1)));

    volatile uint32_t temp = *I2C_SR2;

    /* Step 6: Receive Data */

    while(!(*I2C_SR1 & (1 << 6)));

    data = *I2C_DR;

    /* Step 7: STOP */

    *I2C_CR1 |= (1 << 9);

    while(1)
    {

    }
}
