/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define I2C1_EV_IRQ_NO 31

volatile uint8_t rx_data;

int main(void)
{
    /* Step 1: Enable clocks */

    uint32_t RCC_BASE_ADDR = 0x40023800U;

    uint32_t* RCC_AHB1ENR = (uint32_t*)(RCC_BASE_ADDR + 0x30U);
    uint32_t* RCC_APB1ENR = (uint32_t*)(RCC_BASE_ADDR + 0x40U);

    *RCC_AHB1ENR |= (1 << 1);

    *RCC_APB1ENR |= (1 << 21);

    /* Step 2: Configure GPIO */

    uint32_t GPIOB_BASE_ADDR = 0x40020400U;

    uint32_t* GPIOB_MODER  = (uint32_t*)(GPIOB_BASE_ADDR + 0x00U);

    uint32_t* GPIOB_OTYPER = (uint32_t*)(GPIOB_BASE_ADDR + 0x04U);

    uint32_t* GPIOB_AFRL   = (uint32_t*)(GPIOB_BASE_ADDR + 0x20U);

    *GPIOB_MODER |= (2 << 12) | (2 << 14);

    *GPIOB_OTYPER |= (1 << 6) | (1 << 7);

    *GPIOB_AFRL |= (4 << 24) | (4 << 28);

    /* Step 3: Configure I2C */

    uint32_t I2C1_BASE_ADDR = 0x40005400U;

    uint32_t* I2C_CR1 = (uint32_t*)(I2C1_BASE_ADDR + 0x00U);

    uint32_t* I2C_CR2 = (uint32_t*)(I2C1_BASE_ADDR + 0x04U);

    uint32_t* I2C_CCR = (uint32_t*)(I2C1_BASE_ADDR + 0x1CU);

    uint32_t* I2C_TRISE = (uint32_t*)(I2C1_BASE_ADDR + 0x20U);

    *I2C_CR2 = 16;

    *I2C_CCR = 80;

    *I2C_TRISE = 17;

    /* Interrupt Enable */

    *I2C_CR2 |= (1 << 9);

    *I2C_CR1 |= (1 << 0);

    /* Step 4: NVIC Config */

    uint32_t* NVIC_ISER0 = (uint32_t*)0xE000E100U;

    *NVIC_ISER0 |= (1 << I2C1_EV_IRQ_NO);

    while(1)
    {

    }
}

void I2C1_EV_IRQHandler(void)
{
    uint32_t I2C1_BASE_ADDR = 0x40005400U;

    uint32_t* I2C_SR1 = (uint32_t*)(I2C1_BASE_ADDR + 0x14U);

    uint32_t* I2C_DR  = (uint32_t*)(I2C1_BASE_ADDR + 0x10U);

    if(*I2C_SR1 & (1 << 6))
    {
        rx_data = *I2C_DR;
    }
}
